---
- name: test assert
  hosts: all
  become: true
  tasks:
    - name: make file
      file:
        path: /opt/tools
        state: directory
      when: "inventory_hostname in groups['proxy']"

    - name: stat
      stat:
        path: /opt/tools  
      register: tools
   
    - name: debug
      debug:
        var: tools.stat

    - name: assert
      assert:
        that:
          - tools.stat is defined
        fail_msg: "tool not here"
        success_msg: "tool here"
