---
- name: Install and configure Tomcat and JDK8
  hosts: all
  become: true
  tasks:
    - name: Install JDK8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Tomcat
      yum:
        name: tomcat
        state: present

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes
