---
- name: install docker on rasberry pi
  hosts: zabbix
  become: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.docker_arm
    - geerlingguy.pip

