---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: k3smasters
  become: yes
  roles:
    - role: k3s/master

- hosts: k3sworkers
  become: yes
  roles:
    - role: k3s/node

- hosts: k3smasters
  become: yes
  roles:
    - role: k3s/post
