---
- name: Sysctl with conditional
  hosts: all
  become: true
  tasks:
    - name: set sysctl vw.swappiness variable
      sysctl:
        name: vw.swappiness
        value: '10'
        state: present
      when: [ansible_memfree_mb > 2048]
    

    - name: set sysctl vw.swappiness variable
      debug:
        msg: 'Server memory less than 2048MB'
      when: [ansible_memfree_mb < 2048]

      

...

